name: Renew domain(s)
on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * 1"
  
jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - run: ./freenom.sh -r -a
        env:
          freenom_email: ${{ secrets.FREENOM_EMAIL }}
          freenom_passwd: ${{ secrets.FREENOM_PASSWD }}
          debug: 0
      - run: cat /tmp/freenom.log
